version: '2'

networks:
  # network name
  artxchg2:

services:

  zookeeper0:
    container_name: zookeeper0
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - artxchg2

  zookeeper1:
    container_name: zookeeper1
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - artxchg2

  zookeeper2:
    container_name: zookeeper2
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - artxchg2

  kafka0:
    container_name: kafka0
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 9092:9092
    networks:
      - artxchg2

  kafka1:
    container_name: kafka1
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 10092:9092
    networks:
      - artxchg2

  kafka2:
    container_name: kafka2
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 11092:9092
    networks:
      - artxchg2

  kafka3:
    container_name: kafka3
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 12092:9092
    networks:
      - artxchg2

  orderer0.artxchg2.com:
    container_name: orderer0.artxchg2.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/artxchg2.com/orderers/orderer0.artxchg2.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 7050:7050
    networks:
      - artxchg2

  orderer1.artxchg2.com:
    container_name: orderer1.artxchg2.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/artxchg2.com/orderers/orderer1.artxchg2.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 8050:7050
    networks:
      - artxchg2

  orderer2.artxchg2.com:
    container_name: orderer2.artxchg2.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/artxchg2.com/orderers/orderer2.artxchg2.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 9050:7050
    networks:
      - artxchg2

  peer0.org1.artxchg2.com:
    container_name: peer0.org1.artxchg2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.org1.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.org1.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.artxchg2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/org1.artxchg2.com/peers/peer0.org1.artxchg2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 13051:7051
      - 13053:7053
    depends_on:
      - orderer0.artxchg2.com
      - orderer1.artxchg2.com
      - orderer2.artxchg2.com
    networks:
      - artxchg2

  peer1.org1.artxchg2.com:
    container_name: peer1.org1.artxchg2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.org1.artxchg2.com
      - CORE_PEER_ADDRESS=peer1.org1.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.artxchg2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/org1.artxchg2.com/peers/peer1.org1.artxchg2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 14051:7051
      - 14053:7053
    depends_on:
      - orderer0.artxchg2.com
      - orderer1.artxchg2.com
      - orderer2.artxchg2.com
    networks:
      - artxchg2

  peer0.org2.artxchg2.com:
    container_name: peer0.org2.artxchg2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.org2.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.org2.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.artxchg2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/org2.artxchg2.com/peers/peer0.org2.artxchg2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 15051:7051
      - 15053:7053
    depends_on:
      - orderer0.artxchg2.com
      - orderer1.artxchg2.com
      - orderer2.artxchg2.com
    networks:
      - artxchg2

  peer1.org2.artxchg2.com:
    container_name: peer1.org2.artxchg2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.org2.artxchg2.com
      - CORE_PEER_ADDRESS=peer1.org2.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.artxchg2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/org2.artxchg2.com/peers/peer1.org2.artxchg2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 16051:7051
      - 16053:7053
    depends_on:
      - orderer0.artxchg2.com
      - orderer1.artxchg2.com
      - orderer2.artxchg2.com
    networks:
      - artxchg2

  peer0.org3.artxchg2.com:
    container_name: peer0.org3.artxchg2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.org3.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.org3.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.artxchg2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/org3.artxchg2.com/peers/peer0.org3.artxchg2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 17051:7051
      - 17053:7053
    depends_on:
      - orderer0.artxchg2.com
      - orderer1.artxchg2.com
      - orderer2.artxchg2.com
    networks:
      - artxchg2

  peer0.market.artxchg2.com:
    container_name: peer0.market.artxchg2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.market.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.market.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=ArtMarketMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.market.artxchg2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/market.artxchg2.com/peers/peer0.market.artxchg2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 18051:7051
      - 18053:7053
    depends_on:
      - orderer0.artxchg2.com
      - orderer1.artxchg2.com
      - orderer2.artxchg2.com
    networks:
      - artxchg2

  cli0.Org1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli0.Org1
    environment:
      - CORE_PEER_ID=cli0.org1.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.org1.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.artxchg2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/org1.artxchg2.com:/etc/hyperledger/msp
    depends_on:
      - peer0.org1.artxchg2.com
    networks:
      - artxchg2

  cli1.Org1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli1.Org1
    environment:
      - CORE_PEER_ID=cli1.org1.artxchg2.com
      - CORE_PEER_ADDRESS=peer1.org1.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.artxchg2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/org1.artxchg2.com:/etc/hyperledger/msp
    depends_on:
      - peer1.org1.artxchg2.com
    networks:
      - artxchg2

  cli0.Org2:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli0.Org2
    environment:
      - CORE_PEER_ID=cli0.org2.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.org2.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org2.artxchg2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/org2.artxchg2.com:/etc/hyperledger/msp
    depends_on:
      - peer0.org2.artxchg2.com
    networks:
      - artxchg2

  cli1.Org2:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli1.Org2
    environment:
      - CORE_PEER_ID=cli1.org2.artxchg2.com
      - CORE_PEER_ADDRESS=peer1.org2.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org2.artxchg2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/org2.artxchg2.com:/etc/hyperledger/msp
    depends_on:
      - peer1.org2.artxchg2.com
    networks:
      - artxchg2

  cli0.Org3:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli0.Org3
    environment:
      - CORE_PEER_ID=cli0.org3.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.org3.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org3.artxchg2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/org3.artxchg2.com:/etc/hyperledger/msp
    depends_on:
      - peer0.org3.artxchg2.com
    networks:
      - artxchg2

  cli.ArtMarket:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.ArtMarket
    environment:
      - CORE_PEER_ID=cli.market.artxchg2.com
      - CORE_PEER_ADDRESS=peer0.market.artxchg2.com:7051
      - CORE_PEER_LOCALMSPID=ArtMarketMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@market.artxchg2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/market.artxchg2.com:/etc/hyperledger/msp
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
      - peer0.market.artxchg2.com
    networks:
      - artxchg2
