version: '2'

networks:
  # network name
  lotteryassociation:

services:

  zookeeper0:
    container_name: zookeeper0
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - lotteryassociation

  zookeeper1:
    container_name: zookeeper1
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - lotteryassociation

  zookeeper2:
    container_name: zookeeper2
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - lotteryassociation

  kafka0:
    container_name: kafka0
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 9092:9092
    networks:
      - lotteryassociation

  kafka1:
    container_name: kafka1
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 10092:9092
    networks:
      - lotteryassociation

  kafka2:
    container_name: kafka2
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 11092:9092
    networks:
      - lotteryassociation

  kafka3:
    container_name: kafka3
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 12092:9092
    networks:
      - lotteryassociation

  orderer0.lotteryassociation.com:
    container_name: orderer0.lotteryassociation.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/lotteryassociation.com/orderers/orderer0.lotteryassociation.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 7050:7050
    networks:
      - lotteryassociation

  orderer1.lotteryassociation.com:
    container_name: orderer1.lotteryassociation.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/lotteryassociation.com/orderers/orderer1.lotteryassociation.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 8050:7050
    networks:
      - lotteryassociation

  orderer2.lotteryassociation.com:
    container_name: orderer2.lotteryassociation.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/lotteryassociation.com/orderers/orderer2.lotteryassociation.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 9050:7050
    networks:
      - lotteryassociation

  cdb.Lottery1a:
    container_name: cdbLottery1a
    #image: hyperledger/fabric-couchdb:x86_64-1.0.0
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      DB_URL: http://localhost:5984/
    ports:
      - "5984:5984"
    networks:
      - lotteryassociation

  cdb.Lottery1b:
    container_name: cdbLottery1b
    #image: hyperledger/fabric-couchdb:x86_64-1.0.0
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      DB_URL: http://localhost:5984/
    ports:
      - "5985:5984"
    networks:
      - lotteryassociation

  cdb.Lottery2:
    container_name: cdbLottery2
    #image: hyperledger/fabric-couchdb:x86_64-1.0.0
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      DB_URL: http://localhost:5984/
    ports:
      - "5986:5984"
    networks:
      - lotteryassociation

  cdb.Lottery3:
    container_name: cdbLottery3
    #image: hyperledger/fabric-couchdb:x86_64-1.0.0
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      DB_URL: http://localhost:5984/
    ports:
      - "5987:5984"
    networks:
      - lotteryassociation

  cdb.Regulator:
    container_name: cdbRegulator
    #image: hyperledger/fabric-couchdb:x86_64-1.0.0
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      DB_URL: http://localhost:5984/
    ports:
      - "5988:5984"
    networks:
      - lotteryassociation

  peer0.lottery1.lotteryassociation.com:
    container_name: peer0.lottery1.lotteryassociation.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.lottery1.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.lottery1.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lottery1.lotteryassociation.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=cdbLottery1a:5984
    volumes:
      - ./crypto-config/peerOrganizations/lottery1.lotteryassociation.com/peers/peer0.lottery1.lotteryassociation.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 13051:7051
      - 13052:7052
      - 13053:7053
    depends_on:
      - orderer0.lotteryassociation.com
      - orderer1.lotteryassociation.com
      - orderer2.lotteryassociation.com
      - cdb.Lottery1a
    networks:
      - lotteryassociation

  peer1.lottery1.lotteryassociation.com:
    container_name: peer1.lottery1.lotteryassociation.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.lottery1.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer1.lottery1.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.lottery1.lotteryassociation.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=cdbLottery1b:5984
    volumes:
      - ./crypto-config/peerOrganizations/lottery1.lotteryassociation.com/peers/peer1.lottery1.lotteryassociation.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 14051:7051
      - 14052:7052
      - 14053:7053
    depends_on:
      - orderer0.lotteryassociation.com
      - orderer1.lotteryassociation.com
      - orderer2.lotteryassociation.com
      - cdb.Lottery1b
    networks:
      - lotteryassociation

  peer0.lottery2.lotteryassociation.com:
    container_name: peer0.lottery2.lotteryassociation.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.lottery2.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.lottery2.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lottery2.lotteryassociation.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=cdbLottery2:5984
    volumes:
      - ./crypto-config/peerOrganizations/lottery2.lotteryassociation.com/peers/peer0.lottery2.lotteryassociation.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 15051:7051
      - 15052:7052
      - 15053:7053
    depends_on:
      - orderer0.lotteryassociation.com
      - orderer1.lotteryassociation.com
      - orderer2.lotteryassociation.com
      - cdb.Lottery2
    networks:
      - lotteryassociation

  peer0.lottery3.lotteryassociation.com:
    container_name: peer0.lottery3.lotteryassociation.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.lottery3.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.lottery3.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lottery3.lotteryassociation.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=cdbLottery3:5984
    volumes:
      - ./crypto-config/peerOrganizations/lottery3.lotteryassociation.com/peers/peer0.lottery3.lotteryassociation.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 17051:7051
      - 17052:7052
      - 17053:7053
    depends_on:
      - orderer0.lotteryassociation.com
      - orderer1.lotteryassociation.com
      - orderer2.lotteryassociation.com
      - cdb.Lottery3
    networks:
      - lotteryassociation

  peer0.regulator.lotteryassociation.com:
    container_name: peer0.regulator.lotteryassociation.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.regulator.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.regulator.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulator.lotteryassociation.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=cdbRegulator:5984
    volumes:
      - ./crypto-config/peerOrganizations/regulator.lotteryassociation.com/peers/peer0.regulator.lotteryassociation.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 18051:7051
      - 18052:7052
      - 18053:7053
    depends_on:
      - orderer0.lotteryassociation.com
      - orderer1.lotteryassociation.com
      - orderer2.lotteryassociation.com
      - cdb.Regulator
    networks:
      - lotteryassociation

  cli0.Lottery1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli0.Lottery1
    environment:
      - CORE_PEER_ID=cli0.lottery1.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.lottery1.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@lottery1.lotteryassociation.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/lottery1.lotteryassociation.com:/etc/hyperledger/msp
    depends_on:
      - peer0.lottery1.lotteryassociation.com
    networks:
      - lotteryassociation

  cli1.Lottery1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli1.Lottery1
    environment:
      - CORE_PEER_ID=cli1.lottery1.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer1.lottery1.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@lottery1.lotteryassociation.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/lottery1.lotteryassociation.com:/etc/hyperledger/msp
    depends_on:
      - peer1.lottery1.lotteryassociation.com
    networks:
      - lotteryassociation

  cli0.Lottery2:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli0.Lottery2
    environment:
      - CORE_PEER_ID=cli0.lottery2.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.lottery2.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@lottery2.lotteryassociation.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/lottery2.lotteryassociation.com:/etc/hyperledger/msp
    depends_on:
      - peer0.lottery2.lotteryassociation.com
    networks:
      - lotteryassociation

  cli0.Lottery3:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli0.Lottery3
    environment:
      - CORE_PEER_ID=cli0.lottery3.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.lottery3.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=Lottery3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@lottery3.lotteryassociation.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/lottery3.lotteryassociation.com:/etc/hyperledger/msp
    depends_on:
      - peer0.lottery3.lotteryassociation.com
    networks:
      - lotteryassociation

  cli.Regulator:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Regulator
    environment:
      - CORE_PEER_ID=cli.regulator.lotteryassociation.com
      - CORE_PEER_ADDRESS=peer0.regulator.lotteryassociation.com:7051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@regulator.lotteryassociation.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/regulator.lotteryassociation.com:/etc/hyperledger/msp
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
      - peer0.regulator.lotteryassociation.com
    networks:
      - lotteryassociation
